
name: Rebuild and Commit Docs

on:
  repository_dispatch:
    types: [update-docs]

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Docs Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Rebuild Documentation
        run: |
          npm i
          node scripts/generateRemotePages.js
